package com.tim15.sluzbenik.soap.izjasnjenje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-03T16:29:55.254+02:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://izjasnjenje", name = "IzjasnjenjeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT)
public interface IzjasnjenjeServicePortType {

    @WebMethod(action = "http://izjasnjenje/ws/sendIzjasnjenje")
    public void sendIzjasnjenje(

        @WebParam(partName = "izjasnjenje", name = "izjasnjenje")
        Izjasnjenje izjasnjenje
    );
}
