
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.tim15.sluzbenik.soap.izjasnjenje;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-03T16:29:54.754+02:00
 * Generated source version: 3.4.4
 *
 */

@WebService(
                      serviceName = "IzjasnjenjeService",
                      portName = "IzjasnjenjeServiceSoapBinding",
                      targetNamespace = "http://izjasnjenje",
                      wsdlLocation = "classpath:wsdl/izjasnjenje.wsdl",
                      endpointInterface = "com.tim15.sluzbenik.soap.izjasnjenje.IzjasnjenjeServicePortType")

@Service
public class IzjasnjenjeServiceSoapBindingImpl implements IzjasnjenjeServicePortType {

    private static final Logger LOG = Logger.getLogger(IzjasnjenjeServiceSoapBindingImpl.class.getName());

    @Autowired
    private com.tim15.sluzbenik.service.IzjasnjenjeService izjasnjenjeService;

    /* (non-Javadoc)
     * @see izjasnjenje.IzjasnjenjeServicePortType#sendIzjasnjenje(izjasnjenje.Izjasnjenje izjasnjenje)*
     */

    public void sendIzjasnjenje(Izjasnjenje izjasnjenje) {
        LOG.info("Executing operation sendIzjasnjenje");
        System.out.println(izjasnjenje.getId());
        try {
            izjasnjenjeService.sacuvajIzjasnjenje(izjasnjenje);
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
