package com.tim15.sluzbenik.soap.zahtev;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-09T15:56:26.463+02:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ZahtevServiceSoap",
        wsdlLocation = "classpath:wsdl/zahtev.wsdl",
        targetNamespace = "https://github.com/djordjeognjenovic97/XML-projekat/zahtev")
public class ZahtevServiceSoap extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://github.com/djordjeognjenovic97/XML-projekat/zahtev", "ZahtevServiceSoap");
    public final static QName ZahtevServiceSoapBinding = new QName("https://github.com/djordjeognjenovic97/XML-projekat/zahtev", "ZahtevServiceSoapBinding");
    static {
        URL url = ZahtevServiceSoap.class.getClassLoader().getResource("wsdl/zahtev.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZahtevServiceSoap.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "classpath:wsdl/zahtev.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZahtevServiceSoap(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZahtevServiceSoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZahtevServiceSoap() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZahtevServiceSoap(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZahtevServiceSoap(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZahtevServiceSoap(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZahtevServicePortType
     */
    @WebEndpoint(name = "ZahtevServiceSoapBinding")
    public ZahtevServicePortType getZahtevServiceSoapBinding() {
        return super.getPort(ZahtevServiceSoapBinding, ZahtevServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZahtevServicePortType
     */
    @WebEndpoint(name = "ZahtevServiceSoapBinding")
    public ZahtevServicePortType getZahtevServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ZahtevServiceSoapBinding, ZahtevServicePortType.class, features);
    }

}

