package com.tim15.sluzbenik.soap.zahtev;

import com.tim15.sluzbenik.model.zahtevcir.Zahtev;
import org.springframework.stereotype.Service;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-09T15:56:26.378+02:00
 * Generated source version: 3.4.4
 *
 */

@javax.jws.WebService(
        serviceName = "ZahtevServiceSoap",
        portName = "ZahtevServiceSoapBinding",
        targetNamespace = "https://github.com/djordjeognjenovic97/XML-projekat/zahtev",
        wsdlLocation = "classpath:wsdl/zahtev.wsdl",
        endpointInterface = "com.tim15.sluzbenik.soap.zahtev.ZahtevServicePortType")
@Service
public class ZahtevServiceSoapBindingImpl implements ZahtevServicePortType {

    private static final Logger LOG = Logger.getLogger(ZahtevServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see https.github_com.djordjeognjenovic97.xml_projekat.zahtev.ZahtevServicePortType#getZahtev(java.lang.String id)*
     */
    public Zahtev getZahtev(java.lang.String id) {
        LOG.info("Executing operation getZahtev");
        System.out.println(id);
        try {
            Zahtev _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
