//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.31 at 02:03:23 PM CEST 
//


package com.projekat.poverenik.model.zalbacutanjecir;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.github_com.djordjeognjenovic97.xml_projekat.zalbacutanjecir package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.github_com.djordjeognjenovic97.xml_projekat.zalbacutanjecir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zalbacutanje }
     * 
     */
    public Zalbacutanje createZalbacutanje() {
        return new Zalbacutanje();
    }

    /**
     * Create an instance of {@link TPodnosilacZalbe }
     *
     */
    public TPodnosilacZalbe createTPodnosilacZalbe() {
        return new TPodnosilacZalbe();
    }

    /**
     * Create an instance of {@link TSadrzaj }
     *
     */
    public TSadrzaj createTSadrzaj() {
        return new TSadrzaj();
    }

    /**
     * Create an instance of {@link Zalbacutanje.BrojPredmeta }
     *
     */
    public Zalbacutanje.BrojPredmeta createZalbacutanjeBrojPredmeta() {
        return new Zalbacutanje.BrojPredmeta();
    }

    /**
     * Create an instance of {@link Zalbacutanje.Datum }
     *
     */
    public Zalbacutanje.Datum createZalbacutanjeDatum() {
        return new Zalbacutanje.Datum();
    }

    /**
     * Create an instance of {@link Zalbacutanje.Mesto }
     *
     */
    public Zalbacutanje.Mesto createZalbacutanjeMesto() {
        return new Zalbacutanje.Mesto();
    }

    /**
     * Create an instance of {@link Adresa }
     *
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TPodnosilacZalbe.Ime }
     *
     */
    public TPodnosilacZalbe.Ime createTPodnosilacZalbeIme() {
        return new TPodnosilacZalbe.Ime();
    }

    /**
     * Create an instance of {@link TPodnosilacZalbe.Prezime }
     *
     */
    public TPodnosilacZalbe.Prezime createTPodnosilacZalbePrezime() {
        return new TPodnosilacZalbe.Prezime();
    }

}
