//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.14 at 07:29:18 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/djordjeognjenovic97/XML-projekat/zc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.projekat.poverenik.model.zalbacutanjecir;
