//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 10:47:00 AM CET 
//


package com.projekat.poverenik.model.obavestenjecir;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.obavestenjecir package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TipIznosTroskovaKolicinaNovca_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "kolicina_novca");
    private final static QName _TipUvidGodina_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "godina");
    private final static QName _TipUvidOpisTrazeneInformacije_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "opis_trazene_informacije");
    private final static QName _TipUvidImeDana_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "ime_dana");
    private final static QName _TipUvidBrojSati_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "broj_sati");
    private final static QName _TipUvidPocetakAkcije_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "pocetak_akcije");
    private final static QName _TipUvidKrajAkcije_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "kraj_akcije");
    private final static QName _TipUvidNazivZgrade_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "naziv_zgrade");
    private final static QName _TipUvidNazivUlice_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "naziv_ulice");
    private final static QName _TipUvidBrojUlice_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "broj_ulice");
    private final static QName _TipUvidBrojKancelarije_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenjecir", "broj_kancelarije");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.obavestenjecir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link TipUvid }
     * 
     */
    public TipUvid createTipUvid() {
        return new TipUvid();
    }

    /**
     * Create an instance of {@link Obavestenje.Paragraf }
     * 
     */
    public Obavestenje.Paragraf createObavestenjeParagraf() {
        return new Obavestenje.Paragraf();
    }

    /**
     * Create an instance of {@link TipIznosTroskova }
     * 
     */
    public TipIznosTroskova createTipIznosTroskova() {
        return new TipIznosTroskova();
    }

    /**
     * Create an instance of {@link TipDostavljeno }
     * 
     */
    public TipDostavljeno createTipDostavljeno() {
        return new TipDostavljeno();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "kolicina_novca", scope = TipIznosTroskova.class)
    public JAXBElement<Integer> createTipIznosTroskovaKolicinaNovca(Integer value) {
        return new JAXBElement<Integer>(_TipIznosTroskovaKolicinaNovca_QNAME, Integer.class, TipIznosTroskova.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "godina", scope = TipUvid.class)
    public JAXBElement<XMLGregorianCalendar> createTipUvidGodina(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TipUvidGodina_QNAME, XMLGregorianCalendar.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "opis_trazene_informacije", scope = TipUvid.class)
    public JAXBElement<String> createTipUvidOpisTrazeneInformacije(String value) {
        return new JAXBElement<String>(_TipUvidOpisTrazeneInformacije_QNAME, String.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "ime_dana", scope = TipUvid.class)
    public JAXBElement<String> createTipUvidImeDana(String value) {
        return new JAXBElement<String>(_TipUvidImeDana_QNAME, String.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "broj_sati", scope = TipUvid.class)
    public JAXBElement<Integer> createTipUvidBrojSati(Integer value) {
        return new JAXBElement<Integer>(_TipUvidBrojSati_QNAME, Integer.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "pocetak_akcije", scope = TipUvid.class)
    public JAXBElement<XMLGregorianCalendar> createTipUvidPocetakAkcije(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TipUvidPocetakAkcije_QNAME, XMLGregorianCalendar.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "kraj_akcije", scope = TipUvid.class)
    public JAXBElement<XMLGregorianCalendar> createTipUvidKrajAkcije(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TipUvidKrajAkcije_QNAME, XMLGregorianCalendar.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "naziv_zgrade", scope = TipUvid.class)
    public JAXBElement<String> createTipUvidNazivZgrade(String value) {
        return new JAXBElement<String>(_TipUvidNazivZgrade_QNAME, String.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "naziv_ulice", scope = TipUvid.class)
    public JAXBElement<String> createTipUvidNazivUlice(String value) {
        return new JAXBElement<String>(_TipUvidNazivUlice_QNAME, String.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "broj_ulice", scope = TipUvid.class)
    public JAXBElement<Integer> createTipUvidBrojUlice(Integer value) {
        return new JAXBElement<Integer>(_TipUvidBrojUlice_QNAME, Integer.class, TipUvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", name = "broj_kancelarije", scope = TipUvid.class)
    public JAXBElement<Integer> createTipUvidBrojKancelarije(Integer value) {
        return new JAXBElement<Integer>(_TipUvidBrojKancelarije_QNAME, Integer.class, TipUvid.class, value);
    }

}
