//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 10:47:00 AM CET 
//


package com.projekat.poverenik.model.obavestenjecir;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tipUvid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipUvid"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="godina" type="{http://www.w3.org/2001/XMLSchema}gYear"/&gt;
 *         &lt;element name="opis_trazene_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ime_dana"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Ponedeljak"/&gt;
 *               &lt;enumeration value="Utorak"/&gt;
 *               &lt;enumeration value="Sreda"/&gt;
 *               &lt;enumeration value="Četvrtak"/&gt;
 *               &lt;enumeration value="Petak"/&gt;
 *               &lt;enumeration value="Subota"/&gt;
 *               &lt;enumeration value="Nedelja"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="broj_sati"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="8"/&gt;
 *               &lt;maxInclusive value="21"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="pocetak_akcije"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}time"&gt;
 *               &lt;minInclusive value="08:00:00"/&gt;
 *               &lt;maxInclusive value="20:00:00"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="kraj_akcije"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}time"&gt;
 *               &lt;minInclusive value="09:00:00"/&gt;
 *               &lt;maxInclusive value="21:00:00"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="naziv_zgrade" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="naziv_ulice" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="broj_ulice" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="broj_kancelarije" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipUvid", propOrder = {
    "content"
})
public class TipUvid {

    @XmlElementRefs({
        @XmlElementRef(name = "naziv_zgrade", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "broj_ulice", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "opis_trazene_informacije", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "ime_dana", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "broj_sati", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "pocetak_akcije", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "kraj_akcije", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "naziv_ulice", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "godina", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class),
        @XmlElementRef(name = "broj_kancelarije", namespace = "http://www.ftn.uns.ac.rs/obavestenjecir", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
