package com.projekat.poverenik.soap.izvestaj;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-01T01:49:55.854+02:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "IzvestajService",
                  wsdlLocation = "classpath:wsdl/izvestaj.wsdl",
                  targetNamespace = "https://github.com/djordjeognjenovic97/XML-projekat/izvestaj")
public class IzvestajService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://github.com/djordjeognjenovic97/XML-projekat/izvestaj", "IzvestajService");
    public final static QName IzvestajServiceSoapBinding = new QName("https://github.com/djordjeognjenovic97/XML-projekat/izvestaj", "IzvestajServiceSoapBinding");
    static {
        URL url = IzvestajService.class.getClassLoader().getResource("wsdl/izvestaj.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(IzvestajService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/izvestaj.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IzvestajService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IzvestajService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IzvestajService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IzvestajService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IzvestajService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IzvestajService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IzvestajServicePortType
     */
    @WebEndpoint(name = "IzvestajServiceSoapBinding")
    public IzvestajServicePortType getIzvestajServiceSoapBinding() {
        return super.getPort(IzvestajServiceSoapBinding, IzvestajServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IzvestajServicePortType
     */
    @WebEndpoint(name = "IzvestajServiceSoapBinding")
    public IzvestajServicePortType getIzvestajServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(IzvestajServiceSoapBinding, IzvestajServicePortType.class, features);
    }

}
