//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 10:47:00 AM CET 
//


package com.tim15.sluzbenik.model.zahtevcir;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.zahtevcir package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TipDesnoPInfo_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "p_info");
    private final static QName _TipDesnoPAdresa_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "p_adresa");
    private final static QName _TipDesnoPKontakt_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "p_kontakt");
    private final static QName _TipDesnoPPotpis_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "p_potpis");
    private final static QName _TipKadaDana_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "dana");
    private final static QName _TipKadaGodine_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "godine");
    private final static QName _TipGdeGde_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "gde");
    private final static QName _TipLevoPGde_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "p_gde");
    private final static QName _TipLevoPKada_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "p_kada");
    private final static QName _TipDostavaNacin_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "nacin");
    private final static QName _TipObrazlozenjeDostava_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "dostava");
    private final static QName _TipObrazlozenjeInformacijeODostavi_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "informacije_o_dostavi");
    private final static QName _TipUvodObrazlozenje_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "obrazlozenje");
    private final static QName _TipTeloUvod_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "uvod");
    private final static QName _TipTeloLevo_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "levo");
    private final static QName _TipTeloDesno_QNAME = new QName("http://www.ftn.uns.ac.rs/zahtevcir", "desno");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.zahtevcir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link TipDesno }
     * 
     */
    public TipDesno createTipDesno() {
        return new TipDesno();
    }

    /**
     * Create an instance of {@link Zahtev.Fusnote }
     * 
     */
    public Zahtev.Fusnote createZahtevFusnote() {
        return new Zahtev.Fusnote();
    }

    /**
     * Create an instance of {@link TipHeader }
     *
     */
    public TipHeader createTipHeader() {
        return new TipHeader();
    }

    /**
     * Create an instance of {@link TipTelo }
     * 
     */
    public TipTelo createTipTelo() {
        return new TipTelo();
    }

    /**
     * Create an instance of {@link TipUvod }
     * 
     */
    public TipUvod createTipUvod() {
        return new TipUvod();
    }

    /**
     * Create an instance of {@link TipObrazlozenje }
     * 
     */
    public TipObrazlozenje createTipObrazlozenje() {
        return new TipObrazlozenje();
    }

    /**
     * Create an instance of {@link TipDostava }
     * 
     */
    public TipDostava createTipDostava() {
        return new TipDostava();
    }

    /**
     * Create an instance of {@link TipLevo }
     * 
     */
    public TipLevo createTipLevo() {
        return new TipLevo();
    }

    /**
     * Create an instance of {@link TipGde }
     * 
     */
    public TipGde createTipGde() {
        return new TipGde();
    }

    /**
     * Create an instance of {@link TipKada }
     * 
     */
    public TipKada createTipKada() {
        return new TipKada();
    }

    /**
     * Create an instance of {@link TipDesno.PInfo }
     * 
     */
    public TipDesno.PInfo createTipDesnoPInfo() {
        return new TipDesno.PInfo();
    }

    /**
     * Create an instance of {@link TipDesno.PAdresa }
     * 
     */
    public TipDesno.PAdresa createTipDesnoPAdresa() {
        return new TipDesno.PAdresa();
    }

    /**
     * Create an instance of {@link TipDesno.PKontakt }
     * 
     */
    public TipDesno.PKontakt createTipDesnoPKontakt() {
        return new TipDesno.PKontakt();
    }

    /**
     * Create an instance of {@link TipDesno.PPotpis }
     * 
     */
    public TipDesno.PPotpis createTipDesnoPPotpis() {
        return new TipDesno.PPotpis();
    }

    /**
     * Create an instance of {@link Zahtev.Fusnote.Fusnota }
     * 
     */
    public Zahtev.Fusnote.Fusnota createZahtevFusnoteFusnota() {
        return new Zahtev.Fusnote.Fusnota();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipDesno.PInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "p_info", scope = TipDesno.class)
    public JAXBElement<TipDesno.PInfo> createTipDesnoPInfo(TipDesno.PInfo value) {
        return new JAXBElement<TipDesno.PInfo>(_TipDesnoPInfo_QNAME, TipDesno.PInfo.class, TipDesno.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipDesno.PAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "p_adresa", scope = TipDesno.class)
    public JAXBElement<TipDesno.PAdresa> createTipDesnoPAdresa(TipDesno.PAdresa value) {
        return new JAXBElement<TipDesno.PAdresa>(_TipDesnoPAdresa_QNAME, TipDesno.PAdresa.class, TipDesno.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipDesno.PKontakt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "p_kontakt", scope = TipDesno.class)
    public JAXBElement<TipDesno.PKontakt> createTipDesnoPKontakt(TipDesno.PKontakt value) {
        return new JAXBElement<TipDesno.PKontakt>(_TipDesnoPKontakt_QNAME, TipDesno.PKontakt.class, TipDesno.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipDesno.PPotpis }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "p_potpis", scope = TipDesno.class)
    public JAXBElement<TipDesno.PPotpis> createTipDesnoPPotpis(TipDesno.PPotpis value) {
        return new JAXBElement<TipDesno.PPotpis>(_TipDesnoPPotpis_QNAME, TipDesno.PPotpis.class, TipDesno.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "dana", scope = TipKada.class)
    public JAXBElement<String> createTipKadaDana(String value) {
        return new JAXBElement<String>(_TipKadaDana_QNAME, String.class, TipKada.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "godine", scope = TipKada.class)
    public JAXBElement<String> createTipKadaGodine(String value) {
        return new JAXBElement<String>(_TipKadaGodine_QNAME, String.class, TipKada.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "gde", scope = TipGde.class)
    public JAXBElement<String> createTipGdeGde(String value) {
        return new JAXBElement<String>(_TipGdeGde_QNAME, String.class, TipGde.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipGde }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "p_gde", scope = TipLevo.class)
    public JAXBElement<TipGde> createTipLevoPGde(TipGde value) {
        return new JAXBElement<TipGde>(_TipLevoPGde_QNAME, TipGde.class, TipLevo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipKada }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "p_kada", scope = TipLevo.class)
    public JAXBElement<TipKada> createTipLevoPKada(TipKada value) {
        return new JAXBElement<TipKada>(_TipLevoPKada_QNAME, TipKada.class, TipLevo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "nacin", scope = TipDostava.class)
    public JAXBElement<Object> createTipDostavaNacin(Object value) {
        return new JAXBElement<Object>(_TipDostavaNacin_QNAME, Object.class, TipDostava.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipDostava }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "dostava", scope = TipObrazlozenje.class)
    public JAXBElement<TipDostava> createTipObrazlozenjeDostava(TipDostava value) {
        return new JAXBElement<TipDostava>(_TipObrazlozenjeDostava_QNAME, TipDostava.class, TipObrazlozenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "informacije_o_dostavi", scope = TipObrazlozenje.class)
    public JAXBElement<String> createTipObrazlozenjeInformacijeODostavi(String value) {
        return new JAXBElement<String>(_TipObrazlozenjeInformacijeODostavi_QNAME, String.class, TipObrazlozenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipObrazlozenje }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "obrazlozenje", scope = TipUvod.class)
    public JAXBElement<TipObrazlozenje> createTipUvodObrazlozenje(TipObrazlozenje value) {
        return new JAXBElement<TipObrazlozenje>(_TipUvodObrazlozenje_QNAME, TipObrazlozenje.class, TipUvod.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipUvod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "uvod", scope = TipTelo.class)
    public JAXBElement<TipUvod> createTipTeloUvod(TipUvod value) {
        return new JAXBElement<TipUvod>(_TipTeloUvod_QNAME, TipUvod.class, TipTelo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipLevo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "levo", scope = TipTelo.class)
    public JAXBElement<TipLevo> createTipTeloLevo(TipLevo value) {
        return new JAXBElement<TipLevo>(_TipTeloLevo_QNAME, TipLevo.class, TipTelo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipDesno }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zahtevcir", name = "desno", scope = TipTelo.class)
    public JAXBElement<TipDesno> createTipTeloDesno(TipDesno value) {
        return new JAXBElement<TipDesno>(_TipTeloDesno_QNAME, TipDesno.class, TipTelo.class, value);
    }

}
