//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 10:47:00 AM CET 
//


package com.tim15.sluzbenik.model.zahtevcir;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tipDesno complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipDesno"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="p_info"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="i_malim_slovima" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="p_adresa"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="a_malim_slovima" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="p_kontakt"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="kontakt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="k_malim_slovima" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="p_potpis"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="p_malim_slovima" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipDesno", propOrder = {
    "content"
})
public class TipDesno {

    @XmlElementRefs({
        @XmlElementRef(name = "p_kontakt", namespace = "http://www.ftn.uns.ac.rs/zahtevcir", type = JAXBElement.class),
        @XmlElementRef(name = "p_adresa", namespace = "http://www.ftn.uns.ac.rs/zahtevcir", type = JAXBElement.class),
        @XmlElementRef(name = "p_potpis", namespace = "http://www.ftn.uns.ac.rs/zahtevcir", type = JAXBElement.class),
        @XmlElementRef(name = "p_info", namespace = "http://www.ftn.uns.ac.rs/zahtevcir", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TipDesno.PKontakt }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link TipDesno.PAdresa }{@code >}
     * {@link JAXBElement }{@code <}{@link TipDesno.PPotpis }{@code >}
     * {@link JAXBElement }{@code <}{@link TipDesno.PInfo }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="a_malim_slovima" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adresa",
        "aMalimSlovima"
    })
    public static class PAdresa {

        @XmlElement(required = true)
        protected String adresa;
        @XmlElement(name = "a_malim_slovima", required = true)
        protected String aMalimSlovima;

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdresa(String value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the aMalimSlovima property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAMalimSlovima() {
            return aMalimSlovima;
        }

        /**
         * Sets the value of the aMalimSlovima property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAMalimSlovima(String value) {
            this.aMalimSlovima = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="i_malim_slovima" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "informacije",
        "iMalimSlovima"
    })
    public static class PInfo {

        @XmlElement(required = true)
        protected String informacije;
        @XmlElement(name = "i_malim_slovima", required = true)
        protected String iMalimSlovima;

        /**
         * Gets the value of the informacije property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInformacije() {
            return informacije;
        }

        /**
         * Sets the value of the informacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInformacije(String value) {
            this.informacije = value;
        }

        /**
         * Gets the value of the iMalimSlovima property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIMalimSlovima() {
            return iMalimSlovima;
        }

        /**
         * Sets the value of the iMalimSlovima property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIMalimSlovima(String value) {
            this.iMalimSlovima = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="kontakt" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="k_malim_slovima" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kontakt",
        "kMalimSlovima"
    })
    public static class PKontakt {

        @XmlElement(required = true)
        protected String kontakt;
        @XmlElement(name = "k_malim_slovima", required = true)
        protected String kMalimSlovima;

        /**
         * Gets the value of the kontakt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKontakt() {
            return kontakt;
        }

        /**
         * Sets the value of the kontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKontakt(String value) {
            this.kontakt = value;
        }

        /**
         * Gets the value of the kMalimSlovima property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKMalimSlovima() {
            return kMalimSlovima;
        }

        /**
         * Sets the value of the kMalimSlovima property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKMalimSlovima(String value) {
            this.kMalimSlovima = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="p_malim_slovima" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "potpis",
        "pMalimSlovima"
    })
    public static class PPotpis {

        @XmlElement(required = true)
        protected String potpis;
        @XmlElement(name = "p_malim_slovima", required = true)
        protected String pMalimSlovima;

        /**
         * Gets the value of the potpis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPotpis() {
            return potpis;
        }

        /**
         * Sets the value of the potpis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPotpis(String value) {
            this.potpis = value;
        }

        /**
         * Gets the value of the pMalimSlovima property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPMalimSlovima() {
            return pMalimSlovima;
        }

        /**
         * Sets the value of the pMalimSlovima property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPMalimSlovima(String value) {
            this.pMalimSlovima = value;
        }

    }

}
