//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.11 at 08:57:30 PM CET 
//


package com.tim15.sluzbenik.model.zahtevcir;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="organ" type="{http://www.ftn.uns.ac.rs/zahtevcir}TOrgan"/&gt;
 *         &lt;element name="sadrzaj"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="tipovi_zahteva"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="obavestenje_posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="uvid_dokument" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="kopija_dokument" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="dostavljanje_kopije"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="posta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="elektronska_posta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="faks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="drugi_nacin" minOccurs="0"&gt;
 *                                         &lt;simpleType&gt;
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                             &lt;minLength value="1"/&gt;
 *                                             &lt;maxLength value="100"/&gt;
 *                                           &lt;/restriction&gt;
 *                                         &lt;/simpleType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="informacije_zahtev" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="trazilac_informacije" type="{http://www.ftn.uns.ac.rs/zahtevcir}TTrazilac_informacije"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="mesto" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naziv",
    "organ",
    "sadrzaj",
    "trazilacInformacije"
})
@XmlRootElement(name = "zahtev")
public class Zahtev {

    @XmlElement(required = true)
    protected String naziv;
    @XmlElement(required = true)
    protected TOrgan organ;
    @XmlElement(required = true)
    protected Zahtev.Sadrzaj sadrzaj;
    @XmlElement(name = "trazilac_informacije", required = true)
    protected TTrazilacInformacije trazilacInformacije;
    @XmlAttribute(name = "mesto")
    protected String mesto;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "stanje")
    protected String stanje;

    /**
     * Gets the value of the naziv property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the organ property.
     *
     * @return
     *     possible object is
     *     {@link TOrgan }
     *
     */
    public TOrgan getOrgan() {
        return organ;
    }

    /**
     * Sets the value of the organ property.
     *
     * @param value
     *     allowed object is
     *     {@link TOrgan }
     *
     */
    public void setOrgan(TOrgan value) {
        this.organ = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     *
     * @return
     *     possible object is
     *     {@link Zahtev.Sadrzaj }
     *
     */
    public Zahtev.Sadrzaj getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     *
     * @param value
     *     allowed object is
     *     {@link Zahtev.Sadrzaj }
     *
     */
    public void setSadrzaj(Zahtev.Sadrzaj value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the trazilacInformacije property.
     *
     * @return
     *     possible object is
     *     {@link TTrazilacInformacije }
     *
     */
    public TTrazilacInformacije getTrazilacInformacije() {
        return trazilacInformacije;
    }

    /**
     * Sets the value of the trazilacInformacije property.
     *
     * @param value
     *     allowed object is
     *     {@link TTrazilacInformacije }
     *
     */
    public void setTrazilacInformacije(TTrazilacInformacije value) {
        this.trazilacInformacije = value;
    }

    /**
     * Gets the value of the mesto property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    public String getStanje() {
        return stanje;
    }

    public void setStanje(String stanje) {
        this.stanje = stanje;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="tipovi_zahteva"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="obavestenje_posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="uvid_dokument" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="kopija_dokument" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="dostavljanje_kopije"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="posta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="elektronska_posta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="faks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="drugi_nacin" minOccurs="0"&gt;
     *                               &lt;simpleType&gt;
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                   &lt;minLength value="1"/&gt;
     *                                   &lt;maxLength value="100"/&gt;
     *                                 &lt;/restriction&gt;
     *                               &lt;/simpleType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="informacije_zahtev" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoviZahteva",
        "informacijeZahtev"
    })
    public static class Sadrzaj {

        @XmlElement(name = "tipovi_zahteva", required = true)
        protected Zahtev.Sadrzaj.TipoviZahteva tipoviZahteva;
        @XmlElement(name = "informacije_zahtev", required = true)
        protected String informacijeZahtev;

        /**
         * Gets the value of the tipoviZahteva property.
         *
         * @return
         *     possible object is
         *     {@link Zahtev.Sadrzaj.TipoviZahteva }
         *
         */
        public Zahtev.Sadrzaj.TipoviZahteva getTipoviZahteva() {
            return tipoviZahteva;
        }

        /**
         * Sets the value of the tipoviZahteva property.
         *
         * @param value
         *     allowed object is
         *     {@link Zahtev.Sadrzaj.TipoviZahteva }
         *
         */
        public void setTipoviZahteva(Zahtev.Sadrzaj.TipoviZahteva value) {
            this.tipoviZahteva = value;
        }

        /**
         * Gets the value of the informacijeZahtev property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getInformacijeZahtev() {
            return informacijeZahtev;
        }

        /**
         * Sets the value of the informacijeZahtev property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setInformacijeZahtev(String value) {
            this.informacijeZahtev = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="obavestenje_posedovanje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="uvid_dokument" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="kopija_dokument" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="dostavljanje_kopije"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="posta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="elektronska_posta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="faks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="drugi_nacin" minOccurs="0"&gt;
         *                     &lt;simpleType&gt;
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                         &lt;minLength value="1"/&gt;
         *                         &lt;maxLength value="100"/&gt;
         *                       &lt;/restriction&gt;
         *                     &lt;/simpleType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "obavestenjePosedovanje",
            "uvidDokument",
            "kopijaDokument",
            "dostavljanjeKopije"
        })
        public static class TipoviZahteva {

            @XmlElement(name = "obavestenje_posedovanje")
            protected String obavestenjePosedovanje;
            @XmlElement(name = "uvid_dokument")
            protected String uvidDokument;
            @XmlElement(name = "kopija_dokument")
            protected String kopijaDokument;
            @XmlElement(name = "dostavljanje_kopije")
            protected Zahtev.Sadrzaj.TipoviZahteva.DostavljanjeKopije dostavljanjeKopije;

            /**
             * Gets the value of the obavestenjePosedovanje property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getObavestenjePosedovanje() {
                return obavestenjePosedovanje;
            }

            /**
             * Sets the value of the obavestenjePosedovanje property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setObavestenjePosedovanje(String value) {
                this.obavestenjePosedovanje = value;
            }

            /**
             * Gets the value of the uvidDokument property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getUvidDokument() {
                return uvidDokument;
            }

            /**
             * Sets the value of the uvidDokument property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setUvidDokument(String value) {
                this.uvidDokument = value;
            }

            /**
             * Gets the value of the kopijaDokument property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getKopijaDokument() {
                return kopijaDokument;
            }

            /**
             * Sets the value of the kopijaDokument property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setKopijaDokument(String value) {
                this.kopijaDokument = value;
            }

            /**
             * Gets the value of the dostavljanjeKopije property.
             *
             * @return
             *     possible object is
             *     {@link Zahtev.Sadrzaj.TipoviZahteva.DostavljanjeKopije }
             *
             */
            public Zahtev.Sadrzaj.TipoviZahteva.DostavljanjeKopije getDostavljanjeKopije() {
                return dostavljanjeKopije;
            }

            /**
             * Sets the value of the dostavljanjeKopije property.
             *
             * @param value
             *     allowed object is
             *     {@link Zahtev.Sadrzaj.TipoviZahteva.DostavljanjeKopije }
             *
             */
            public void setDostavljanjeKopije(Zahtev.Sadrzaj.TipoviZahteva.DostavljanjeKopije value) {
                this.dostavljanjeKopije = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="posta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="elektronska_posta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="faks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="drugi_nacin" minOccurs="0"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *               &lt;minLength value="1"/&gt;
             *               &lt;maxLength value="100"/&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "posta",
                "elektronskaPosta",
                "faks",
                "drugiNacin"
            })
            public static class DostavljanjeKopije {

                protected String posta;
                @XmlElement(name = "elektronska_posta")
                protected String elektronskaPosta;
                protected String faks;
                @XmlElement(name = "drugi_nacin")
                protected String drugiNacin;

                /**
                 * Gets the value of the posta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPosta() {
                    return posta;
                }

                /**
                 * Sets the value of the posta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPosta(String value) {
                    this.posta = value;
                }

                /**
                 * Gets the value of the elektronskaPosta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getElektronskaPosta() {
                    return elektronskaPosta;
                }

                /**
                 * Sets the value of the elektronskaPosta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setElektronskaPosta(String value) {
                    this.elektronskaPosta = value;
                }

                /**
                 * Gets the value of the faks property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFaks() {
                    return faks;
                }

                /**
                 * Sets the value of the faks property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFaks(String value) {
                    this.faks = value;
                }

                /**
                 * Gets the value of the drugiNacin property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDrugiNacin() {
                    return drugiNacin;
                }

                /**
                 * Sets the value of the drugiNacin property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDrugiNacin(String value) {
                    this.drugiNacin = value;
                }

            }

        }

    }

}
