//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.17 at 11:22:07 AM CEST 
//


package com.tim15.sluzbenik.model.obavestenjecir;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="organ"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="sediste_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="podnosilac_obavestenja"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="fizicko_lice"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="adresa" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}adresa"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="pravno_lice"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="adresa" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}adresa"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uvid" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}tipUvid"/&gt;
 *         &lt;element name="iznos_troskova" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="dostavljeno" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}tipDostavljeno"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="broj_predmeta" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organ",
    "podnosilacObavestenja",
    "naslov",
    "uvid",
    "iznosTroskova",
    "dostavljeno"
})
@XmlRootElement(name = "obavestenje")
public class Obavestenje {

    @XmlElement(required = true)
    protected Obavestenje.Organ organ;
    @XmlElement(name = "podnosilac_obavestenja", required = true)
    protected Obavestenje.PodnosilacObavestenja podnosilacObavestenja;
    @XmlElement(required = true)
    protected String naslov;
    @XmlElement(required = true)
    protected TipUvid uvid;
    @XmlElement(name = "iznos_troskova")
    protected double iznosTroskova;
    @XmlElement(required = true)
    protected TipDostavljeno dostavljeno;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "broj_predmeta")
    protected Integer brojPredmeta;

    /**
     * Gets the value of the organ property.
     *
     * @return
     *     possible object is
     *     {@link Obavestenje.Organ }
     *
     */
    public Obavestenje.Organ getOrgan() {
        return organ;
    }

    /**
     * Sets the value of the organ property.
     *
     * @param value
     *     allowed object is
     *     {@link Obavestenje.Organ }
     *
     */
    public void setOrgan(Obavestenje.Organ value) {
        this.organ = value;
    }

    /**
     * Gets the value of the podnosilacObavestenja property.
     *
     * @return
     *     possible object is
     *     {@link Obavestenje.PodnosilacObavestenja }
     *
     */
    public Obavestenje.PodnosilacObavestenja getPodnosilacObavestenja() {
        return podnosilacObavestenja;
    }

    /**
     * Sets the value of the podnosilacObavestenja property.
     *
     * @param value
     *     allowed object is
     *     {@link Obavestenje.PodnosilacObavestenja }
     *
     */
    public void setPodnosilacObavestenja(Obavestenje.PodnosilacObavestenja value) {
        this.podnosilacObavestenja = value;
    }

    /**
     * Gets the value of the naslov property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the uvid property.
     *
     * @return
     *     possible object is
     *     {@link TipUvid }
     *
     */
    public TipUvid getUvid() {
        return uvid;
    }

    /**
     * Sets the value of the uvid property.
     *
     * @param value
     *     allowed object is
     *     {@link TipUvid }
     *
     */
    public void setUvid(TipUvid value) {
        this.uvid = value;
    }

    /**
     * Gets the value of the iznosTroskova property.
     *
     */
    public double getIznosTroskova() {
        return iznosTroskova;
    }

    /**
     * Sets the value of the iznosTroskova property.
     *
     */
    public void setIznosTroskova(double value) {
        this.iznosTroskova = value;
    }

    /**
     * Gets the value of the dostavljeno property.
     *
     * @return
     *     possible object is
     *     {@link TipDostavljeno }
     *
     */
    public TipDostavljeno getDostavljeno() {
        return dostavljeno;
    }

    /**
     * Sets the value of the dostavljeno property.
     *
     * @param value
     *     allowed object is
     *     {@link TipDostavljeno }
     *
     */
    public void setDostavljeno(TipDostavljeno value) {
        this.dostavljeno = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the brojPredmeta property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getBrojPredmeta() {
        return brojPredmeta;
    }

    /**
     * Sets the value of the brojPredmeta property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setBrojPredmeta(Integer value) {
        this.brojPredmeta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="sediste_organa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivOrgana",
        "sedisteOrgana"
    })
    public static class Organ {

        @XmlElement(name = "naziv_organa", required = true)
        protected String nazivOrgana;
        @XmlElement(name = "sediste_organa", required = true)
        protected String sedisteOrgana;

        /**
         * Gets the value of the nazivOrgana property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getNazivOrgana() {
            return nazivOrgana;
        }

        /**
         * Sets the value of the nazivOrgana property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setNazivOrgana(String value) {
            this.nazivOrgana = value;
        }

        /**
         * Gets the value of the sedisteOrgana property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSedisteOrgana() {
            return sedisteOrgana;
        }

        /**
         * Sets the value of the sedisteOrgana property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSedisteOrgana(String value) {
            this.sedisteOrgana = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="fizicko_lice"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="adresa" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}adresa"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="pravno_lice"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="adresa" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}adresa"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fizickoLice",
        "pravnoLice"
    })
    public static class PodnosilacObavestenja {

        @XmlElement(name = "fizicko_lice")
        protected Obavestenje.PodnosilacObavestenja.FizickoLice fizickoLice;
        @XmlElement(name = "pravno_lice")
        protected Obavestenje.PodnosilacObavestenja.PravnoLice pravnoLice;

        /**
         * Gets the value of the fizickoLice property.
         *
         * @return
         *     possible object is
         *     {@link Obavestenje.PodnosilacObavestenja.FizickoLice }
         *
         */
        public Obavestenje.PodnosilacObavestenja.FizickoLice getFizickoLice() {
            return fizickoLice;
        }

        /**
         * Sets the value of the fizickoLice property.
         *
         * @param value
         *     allowed object is
         *     {@link Obavestenje.PodnosilacObavestenja.FizickoLice }
         *
         */
        public void setFizickoLice(Obavestenje.PodnosilacObavestenja.FizickoLice value) {
            this.fizickoLice = value;
        }

        /**
         * Gets the value of the pravnoLice property.
         *
         * @return
         *     possible object is
         *     {@link Obavestenje.PodnosilacObavestenja.PravnoLice }
         *
         */
        public Obavestenje.PodnosilacObavestenja.PravnoLice getPravnoLice() {
            return pravnoLice;
        }

        /**
         * Sets the value of the pravnoLice property.
         *
         * @param value
         *     allowed object is
         *     {@link Obavestenje.PodnosilacObavestenja.PravnoLice }
         *
         */
        public void setPravnoLice(Obavestenje.PodnosilacObavestenja.PravnoLice value) {
            this.pravnoLice = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="adresa" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}adresa"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "adresa"
        })
        public static class FizickoLice {

            @XmlElement(required = true)
            protected String ime;
            @XmlElement(required = true)
            protected String prezime;
            @XmlElement(required = true)
            protected Adresa adresa;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link Adresa }
             *     
             */
            public Adresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link Adresa }
             *     
             */
            public void setAdresa(Adresa value) {
                this.adresa = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="adresa" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}adresa"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naziv",
            "adresa"
        })
        public static class PravnoLice {

            @XmlElement(required = true)
            protected String naziv;
            @XmlElement(required = true)
            protected Adresa adresa;

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link Adresa }
             *     
             */
            public Adresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link Adresa }
             *     
             */
            public void setAdresa(Adresa value) {
                this.adresa = value;
            }

        }

    }

}
