//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.17 at 11:22:07 AM CEST 
//


package com.tim15.sluzbenik.model.obavestenjecir;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.github_com.djordjeognjenovic97.xml_projekat.obavestenjecir package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.github_com.djordjeognjenovic97.xml_projekat.obavestenjecir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     *
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link TipDostavljeno }
     *
     */
    public TipDostavljeno createTipDostavljeno() {
        return new TipDostavljeno();
    }

    /**
     * Create an instance of {@link Obavestenje.PodnosilacObavestenja }
     *
     */
    public Obavestenje.PodnosilacObavestenja createObavestenjePodnosilacObavestenja() {
        return new Obavestenje.PodnosilacObavestenja();
    }

    /**
     * Create an instance of {@link Obavestenje.Organ }
     *
     */
    public Obavestenje.Organ createObavestenjeOrgan() {
        return new Obavestenje.Organ();
    }

    /**
     * Create an instance of {@link TipUvid }
     *
     */
    public TipUvid createTipUvid() {
        return new TipUvid();
    }

    /**
     * Create an instance of {@link Adresa }
     *
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TipDostavljeno.OpcijaDostave }
     *
     */
    public TipDostavljeno.OpcijaDostave createTipDostavljenoOpcijaDostave() {
        return new TipDostavljeno.OpcijaDostave();
    }

    /**
     * Create an instance of {@link Obavestenje.PodnosilacObavestenja.FizickoLice }
     *
     */
    public Obavestenje.PodnosilacObavestenja.FizickoLice createObavestenjePodnosilacObavestenjaFizickoLice() {
        return new Obavestenje.PodnosilacObavestenja.FizickoLice();
    }

    /**
     * Create an instance of {@link Obavestenje.PodnosilacObavestenja.PravnoLice }
     *
     */
    public Obavestenje.PodnosilacObavestenja.PravnoLice createObavestenjePodnosilacObavestenjaPravnoLice() {
        return new Obavestenje.PodnosilacObavestenja.PravnoLice();
    }

}
