//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.17 at 11:22:07 AM CEST 
//


package com.tim15.sluzbenik.model.obavestenjecir;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tipUvid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipUvid"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="godina" type="{http://www.w3.org/2001/XMLSchema}gYear"/&gt;
 *         &lt;element name="opis_trazene_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ime_dana"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Ponedeljak"/&gt;
 *               &lt;enumeration value="Utorak"/&gt;
 *               &lt;enumeration value="Sreda"/&gt;
 *               &lt;enumeration value="Četvrtak"/&gt;
 *               &lt;enumeration value="Petak"/&gt;
 *               &lt;enumeration value="Subota"/&gt;
 *               &lt;enumeration value="Nedelja"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="broj_sati"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="8"/&gt;
 *               &lt;maxInclusive value="21"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="pocetak_akcije"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}time"&gt;
 *               &lt;minInclusive value="08:00:00"/&gt;
 *               &lt;maxInclusive value="20:00:00"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="kraj_akcije"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}time"&gt;
 *               &lt;minInclusive value="09:00:00"/&gt;
 *               &lt;maxInclusive value="21:00:00"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="adresa" type="{https://github.com/djordjeognjenovic97/XML-projekat/obavestenjecir}adresa"/&gt;
 *         &lt;element name="broj_kancelarije" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipUvid", propOrder = {
    "godina",
    "opisTrazeneInformacije",
    "imeDana",
    "brojSati",
    "pocetakAkcije",
    "krajAkcije",
    "adresa",
    "brojKancelarije"
})
public class TipUvid {

    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar godina;
    @XmlElement(name = "opis_trazene_informacije", required = true)
    protected String opisTrazeneInformacije;
    @XmlElement(name = "ime_dana", required = true, nillable = true)
    protected String imeDana;
    @XmlElement(name = "broj_sati", required = true, type = Integer.class, nillable = true)
    protected Integer brojSati;
    @XmlElement(name = "pocetak_akcije", required = true, nillable = true)
    protected XMLGregorianCalendar pocetakAkcije;
    @XmlElement(name = "kraj_akcije", required = true, nillable = true)
    protected XMLGregorianCalendar krajAkcije;
    @XmlElement(required = true)
    protected Adresa adresa;
    @XmlElement(name = "broj_kancelarije", required = true, nillable = true)
    protected String brojKancelarije;

    /**
     * Gets the value of the godina property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getGodina() {
        return godina;
    }

    /**
     * Sets the value of the godina property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setGodina(XMLGregorianCalendar value) {
        this.godina = value;
    }

    /**
     * Gets the value of the opisTrazeneInformacije property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOpisTrazeneInformacije() {
        return opisTrazeneInformacije;
    }

    /**
     * Sets the value of the opisTrazeneInformacije property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOpisTrazeneInformacije(String value) {
        this.opisTrazeneInformacije = value;
    }

    /**
     * Gets the value of the imeDana property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getImeDana() {
        return imeDana;
    }

    /**
     * Sets the value of the imeDana property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setImeDana(String value) {
        this.imeDana = value;
    }

    /**
     * Gets the value of the brojSati property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getBrojSati() {
        return brojSati;
    }

    /**
     * Sets the value of the brojSati property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setBrojSati(Integer value) {
        this.brojSati = value;
    }

    /**
     * Gets the value of the pocetakAkcije property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getPocetakAkcije() {
        return pocetakAkcije;
    }

    /**
     * Sets the value of the pocetakAkcije property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setPocetakAkcije(XMLGregorianCalendar value) {
        this.pocetakAkcije = value;
    }

    /**
     * Gets the value of the krajAkcije property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getKrajAkcije() {
        return krajAkcije;
    }

    /**
     * Sets the value of the krajAkcije property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setKrajAkcije(XMLGregorianCalendar value) {
        this.krajAkcije = value;
    }

    /**
     * Gets the value of the adresa property.
     *
     * @return
     *     possible object is
     *     {@link Adresa }
     *
     */
    public Adresa getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     *
     * @param value
     *     allowed object is
     *     {@link Adresa }
     *     
     */
    public void setAdresa(Adresa value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the brojKancelarije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojKancelarije() {
        return brojKancelarije;
    }

    /**
     * Sets the value of the brojKancelarije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojKancelarije(String value) {
        this.brojKancelarije = value;
    }

}
