//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.11 at 08:57:30 PM CET 
//


package com.tim15.sluzbenik.model.zalbacutanjecir;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.zalbacutanjecir package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.zalbacutanjecir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zalbacutanje }
     *
     */
    public Zalbacutanje createZalbacutanje() {
        return new Zalbacutanje();
    }

    /**
     * Create an instance of {@link TPrimalacZalbe }
     *
     */
    public TPrimalacZalbe createTPrimalacZalbe() {
        return new TPrimalacZalbe();
    }

    /**
     * Create an instance of {@link TSadrzaj }
     *
     */
    public TSadrzaj createTSadrzaj() {
        return new TSadrzaj();
    }

    /**
     * Create an instance of {@link TPodnosilacZalbe }
     *
     */
    public TPodnosilacZalbe createTPodnosilacZalbe() {
        return new TPodnosilacZalbe();
    }

    /**
     * Create an instance of {@link Adresa }
     *
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

}
