SELECT * FROM <http://localhost:8081/fusekiSluzbenik/zahtevi/data/zahtevi> WHERE {
 ?subject <http://www.ftn.uns.ac.rs/rdf/examples/predicate/id> ?id .
  ?subject <http://www.ftn.uns.ac.rs/rdf/examples/predicate/datum> ?datum .
  ?subject <http://www.ftn.uns.ac.rs/rdf/examples/predicate/mesto> ?mesto .
  ?subject <http://www.ftn.uns.ac.rs/rdf/examples/predicate/naziv> ?nazivOrgana .
  FILTER( CONTAINS(UCASE(str(?id)), UCASE("{{id}}"))
    && CONTAINS(UCASE(str(?datum)), UCASE("{{datum}}"))
    && CONTAINS(UCASE(str(?mesto)), UCASE("{{mesto}}"))
    && CONTAINS(UCASE(str(?nazivOrgana)), UCASE("{{nazivOrgana}}"))
  ) .
}