//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.19 at 05:52:25 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/djordjeognjenovic97/XML-projekat/izvestaji", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.projekat.poverenik.model.izvestaji;
