
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.soap;

import com.example.demo.model.Email;
import com.example.demo.soap.EmailServicePortType;
import com.example.demo.service.EmailService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-10T13:20:28.551+02:00
 * Generated source version: 3.4.4
 *
 */

@WebService(
                      serviceName = "EmailService",
                      portName = "EmailServiceSoapBinding",
                      targetNamespace = "http://email",
                      wsdlLocation = "classpath:wsdl/email.wsdl",
                      endpointInterface = "com.example.demo.soap.EmailServicePortType")
@Service
public class EmailServiceSoapBindingImpl implements EmailServicePortType {

    @Autowired
    EmailService emailService;

    private static final Logger LOG = Logger.getLogger(EmailServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see email.EmailServicePortType#sendEmail(email.Email email)*
     */
    public void sendEmail(Email email) {
        LOG.info("Executing operation sendEmail");
        try {
            emailService.send(email);
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
