package com.example.demo.soap;

import com.example.demo.model.Email;
import com.example.demo.model.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-08-10T13:20:28.645+02:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://email", name = "EmailServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT)
public interface EmailServicePortType {

    @WebMethod(action = "http://email/ws/sendEmail")
    public void sendEmail(

        @WebParam(partName = "email", name = "email")
                Email email
    );
}
