
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.projekat.poverenik.soap;

import org.springframework.stereotype.Service;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-01T01:49:55.776+02:00
 * Generated source version: 3.4.4
 *
 */

@WebService(
                      serviceName = "IzvestajService",
                      portName = "IzvestajServiceSoapBinding",
                      targetNamespace = "https://github.com/djordjeognjenovic97/XML-projekat/izvestaj",
                      wsdlLocation = "classpath:wsdl/izvestaj.wsdl",
                      endpointInterface = "com.projekat.poverenik.soap.IzvestajServicePortType")
@Service
public class IzvestajServiceSoapBindingImpl implements IzvestajServicePortType {

    private static final Logger LOG = Logger.getLogger(IzvestajServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see https.github_com.djordjeognjenovic97.xml_projekat.izvestaj.IzvestajServicePortType#sendIzvestaj(https.github_com.djordjeognjenovic97.xml_projekat.izvestaj.Izvestaj izvestaj)*
     */
    public void sendIzvestaj(Izvestaj izvestaj) {
        LOG.info("Executing operation sendIzvestaj");
        System.out.println(izvestaj.getDatum().getValue());
        System.out.println(izvestaj.getId());
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
