package com.tim15.sluzbenik.soap.resenje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-07T11:51:58.929+02:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "https://github.com/djordjeognjenovic97/XML-projekat/resenja", name = "ResenjeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT)
public interface ResenjeServicePortType {

    @WebMethod(action = "http://resenje/ws/sendResenje")
    public void sendResenje(

        @WebParam(partName = "resenje", name = "resenje")
        Resenje resenje
    );
}
