
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.tim15.sluzbenik.soap.resenje;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-07T11:51:58.851+02:00
 * Generated source version: 3.4.4
 *
 */

@WebService(
                      serviceName = "ResenjeService",
                      portName = "ResenjeServiceSoapBinding",
                      targetNamespace = "https://github.com/djordjeognjenovic97/XML-projekat/resenja",
                      wsdlLocation = "classpath:wsdl/resenje.wsdl",
                      endpointInterface = "com.tim15.sluzbenik.soap.resenje.ResenjeServicePortType")

@Service
public class ResenjeServiceSoapBindingImpl implements ResenjeServicePortType {

    private static final Logger LOG = Logger.getLogger(ResenjeServiceSoapBindingImpl.class.getName());

    @Autowired
    private com.tim15.sluzbenik.service.ResenjaService resenjeService;

    /* (non-Javadoc)
     * @see https.github_com.djordjeognjenovic97.xml_projekat.resenja.ResenjeServicePortType#sendResenje(https.github_com.djordjeognjenovic97.xml_projekat.resenja.Resenje resenje)*
     */
    public void sendResenje(Resenje resenje) {
        LOG.info("Executing operation sendResenje");
        System.out.println(resenje);
        System.out.println(resenje.getId());
        try {
            resenjeService.sacuvajResenje(resenje);
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
