package com.tim15.sluzbenik.soap.resenje;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-09-07T11:51:58.944+02:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ResenjeService",
                  wsdlLocation = "classpath:wsdl/resenje.wsdl",
                  targetNamespace = "https://github.com/djordjeognjenovic97/XML-projekat/resenja")
public class ResenjeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://github.com/djordjeognjenovic97/XML-projekat/resenja", "ResenjeService");
    public final static QName ResenjeServiceSoapBinding = new QName("https://github.com/djordjeognjenovic97/XML-projekat/resenja", "ResenjeServiceSoapBinding");
    static {
        URL url = ResenjeService.class.getClassLoader().getResource("wsdl/resenje.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ResenjeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/resenje.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ResenjeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ResenjeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResenjeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ResenjeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ResenjeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ResenjeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ResenjeServicePortType
     */
    @WebEndpoint(name = "ResenjeServiceSoapBinding")
    public ResenjeServicePortType getResenjeServiceSoapBinding() {
        return super.getPort(ResenjeServiceSoapBinding,ResenjeServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResenjeServicePortType
     */
    @WebEndpoint(name = "ResenjeServiceSoapBinding")
    public ResenjeServicePortType getResenjeServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ResenjeServiceSoapBinding, ResenjeServicePortType.class, features);
    }

}
